name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y python3-dev python3-pil
    - name: Build
      run: python3 setup.py build